import { z } from "zod";
import { type ProductCapabilities } from "./product-capabilities.js";
export declare const apiEnvSchema: z.ZodObject<{
    DATABASE_URL: z.ZodString;
    EXTERNAL_HEALTHCHECK_URLS: z.ZodDefault<z.ZodString>;
    GOOGLE_CLIENT_ID: z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodOptional<z.ZodString>>;
    GOOGLE_CLIENT_SECRET: z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodOptional<z.ZodString>>;
    GOOGLE_REDIRECT_URI: z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodOptional<z.ZodString>>;
    HUBSPOT_CLIENT_ID: z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodOptional<z.ZodString>>;
    HUBSPOT_CLIENT_SECRET: z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodOptional<z.ZodString>>;
    HUBSPOT_REDIRECT_URI: z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodOptional<z.ZodString>>;
    JOB_HMAC_GLOBAL_SECRET: z.ZodDefault<z.ZodString>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<{
        error: "error";
        fatal: "fatal";
        warn: "warn";
        info: "info";
        debug: "debug";
        trace: "trace";
    }>>;
    MICROSOFT_CLIENT_ID: z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodOptional<z.ZodString>>;
    MICROSOFT_CLIENT_SECRET: z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodOptional<z.ZodString>>;
    MICROSOFT_REDIRECT_URI: z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodOptional<z.ZodString>>;
    NODE_ENV: z.ZodDefault<z.ZodEnum<{
        development: "development";
        test: "test";
        production: "production";
    }>>;
    REQUIRE_SECURE_COOKIES: z.ZodDefault<z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodBoolean>>;
    OTEL_EXPORTER_OTLP_ENDPOINT: z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodOptional<z.ZodString>>;
    OTEL_SERVICE_NAME: z.ZodDefault<z.ZodString>;
    QUEUE_BACKPRESSURE_THRESHOLD: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    QUEUE_NAME: z.ZodDefault<z.ZodString>;
    REDIS_URL: z.ZodString;
    TENANT_QUEUE_RATE_LIMIT_MAX: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    TENANT_QUEUE_RATE_LIMIT_WINDOW_SECONDS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    SENTRY_DSN: z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodOptional<z.ZodString>>;
    SENTRY_ENVIRONMENT: z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodOptional<z.ZodString>>;
    SESSION_SECRET: z.ZodDefault<z.ZodString>;
    STRIPE_CANCEL_URL: z.ZodDefault<z.ZodString>;
    STRIPE_DECLINE_BAN_THRESHOLD: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    STRIPE_PORTAL_RETURN_URL: z.ZodDefault<z.ZodString>;
    STRIPE_SECRET_KEY: z.ZodDefault<z.ZodString>;
    STRIPE_SUCCESS_URL: z.ZodDefault<z.ZodString>;
    STRIPE_TEMP_BAN_SECONDS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    STRIPE_WEBHOOK_TOLERANCE_SECONDS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    STRIPE_WEBHOOK_SECRET: z.ZodDefault<z.ZodString>;
    UPTIMEROBOT_API_TOKEN: z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodOptional<z.ZodString>>;
    WEB_BASE_URL: z.ZodDefault<z.ZodString>;
    BIRTHUB_ENABLE_CLINICAL_WORKSPACE: z.ZodDefault<z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodBoolean>>;
    BIRTHUB_ENABLE_FHIR_FACADE: z.ZodDefault<z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodBoolean>>;
    BIRTHUB_ENABLE_PRIVACY_ADVANCED: z.ZodDefault<z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodBoolean>>;
    BIRTHUB_ENABLE_PRIVACY_SELF_SERVICE: z.ZodDefault<z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodBoolean>>;
    ALLOW_LEGACY_PLAINTEXT_CONNECTOR_SECRETS: z.ZodDefault<z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodBoolean>>;
    API_AUTH_COOKIE_NAME: z.ZodDefault<z.ZodString>;
    API_AUTH_COOKIE_DOMAIN: z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodOptional<z.ZodString>>;
    API_AUTH_IDLE_TIMEOUT_MINUTES: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    API_AUTH_REFRESH_COOKIE_NAME: z.ZodDefault<z.ZodString>;
    API_AUTH_ROTATION_GRACE_HOURS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    API_AUTH_SESSION_TTL_HOURS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    API_AUTH_TOKEN_TTL_MINUTES: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    AUTH_BCRYPT_SALT_ROUNDS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    API_CORS_ORIGINS: z.ZodDefault<z.ZodString>;
    API_CSRF_COOKIE_NAME: z.ZodDefault<z.ZodString>;
    API_CSRF_HEADER_NAME: z.ZodDefault<z.ZodString>;
    API_HANDLER_TIMEOUT_MS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    API_JSON_BODY_LIMIT: z.ZodDefault<z.ZodString>;
    API_KEY_PREFIX: z.ZodDefault<z.ZodString>;
    API_KEY_RATE_LIMIT_MAX: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    API_LOGIN_RATE_LIMIT_MAX: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    API_LOGIN_RATE_LIMIT_WINDOW_MS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    API_PORT: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    API_RATE_LIMIT_MAX: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    API_RATE_LIMIT_WINDOW_MS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    API_WEBHOOK_RATE_LIMIT_MAX: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    API_WEBHOOK_RATE_LIMIT_TENANT_MULTIPLIER: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    API_WEBHOOK_RATE_LIMIT_WINDOW_MS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    AUTH_MFA_CHALLENGE_TTL_SECONDS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    AUTH_MFA_CLOCK_SKEW_WINDOWS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    AUTH_MFA_ENCRYPTION_KEY: z.ZodDefault<z.ZodString>;
    AUTH_MFA_ISSUER: z.ZodDefault<z.ZodString>;
    BILLING_GRACE_PERIOD_DAYS: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
}, z.core.$strip>;
export type ApiConfig = z.infer<typeof apiEnvSchema> & {
    corsOrigins: string[];
    externalHealthcheckUrls: string[];
} & ProductCapabilities;
export declare function getApiConfig(env?: NodeJS.ProcessEnv): ApiConfig;
