import type { SupportedLocale } from "../../lib/i18n";

import type {
  SdrAutomaticCopy,
  SdrAutomaticLead,
  SdrAutomaticTimeSlot
} from "./sdr-automatic-data";

export const SDR_AUTOMATIC_COPY: Record<SupportedLocale, SdrAutomaticCopy> = {
  "en-US": {
    actionPrimary: "Send to closer",
    agendaCaption: "Three best-fit slots based on segment, conversion history, and calendar load.",
    agendaHelper: "Recommended closer",
    agendaSubtitle: "Schedule the demo with the best closer for the account.",
    agendaTitle: "Co-pilot: Intelligent Scheduler",
    assistantHint: "Qualification call with Julia Andrade at Connecta Corp.",
    assistantSubtitle: "Conversation support grounded in SPIN Selling.",
    assistantTitle: "Co-pilot: Method Assistant",
    callFocus: "Live notes",
    handoffSubtitle: "Give the closer enough context to enter the meeting with precision.",
    handoffTitle: "Co-pilot: Handoff Briefing",
    heroDescription:
      "Interactive prototype of the SDR Automatic 360 platform inside the BirthHub Sales OS.",
    heroEyebrow: "SDR Platform",
    heroTitle: "BirthHub 360 SDR Automatic",
    leadSubtitle: "Rank the hottest opportunities before the queue gets noisy.",
    leadTitle: "Co-pilot: Predictive Lead Score",
    metrics: [
      { label: "Critical leads", value: "06" },
      { label: "Calls this morning", value: "11" },
      { label: "Meetings in pipeline", value: "04" }
    ],
    moduleLabel: "SDR module",
    nextStepLabel: "Next move",
    quickBrief: "Account signal",
    salesRepName: "Lucas Mendes",
    salesRepRole: "SDR",
    sidebarTitle: "Birth Hub 360",
    spinLabel: "SPIN guidance",
    summaryLabel: "Conversion path",
    tableAction: "Action",
    tableLead: "Lead",
    tablePriority: "Priority",
    tableScore: "Lead score",
    tableSource: "Source",
    timelineLabel: "Calendar fit"
  },
  "pt-BR": {
    actionPrimary: "Enviar para o closer",
    agendaCaption: "Tres melhores horarios com base em segmento, historico de conversao e carga de agenda.",
    agendaHelper: "Closer recomendado",
    agendaSubtitle: "Agende a demonstracao com o closer certo para essa conta.",
    agendaTitle: "Co-piloto: Agendador Inteligente",
    assistantHint: "Ligacao de qualificacao com Julia Andrade na Connecta Corp.",
    assistantSubtitle: "Suporte de conversa orientado por SPIN Selling.",
    assistantTitle: "Co-piloto: Assistente Metodologico",
    callFocus: "Anotacoes da chamada",
    handoffSubtitle: "Entregue contexto suficiente para o closer entrar na reuniao com precisao.",
    handoffTitle: "Co-piloto: Briefing de Handoff",
    heroDescription:
      "Prototipo interativo da plataforma SDR Automatic 360 dentro do ecossistema Sales OS da BirthHub.",
    heroEyebrow: "Plataforma SDR",
    heroTitle: "BirthHub 360 SDR Automatic",
    leadSubtitle: "Priorize as oportunidades mais quentes antes que a fila fique ruidosa.",
    leadTitle: "Co-piloto: Lead Score Preditivo",
    metrics: [
      { label: "Leads criticos", value: "06" },
      { label: "Ligacoes hoje cedo", value: "11" },
      { label: "Reunioes no pipeline", value: "04" }
    ],
    moduleLabel: "Modulo SDR",
    nextStepLabel: "Proximo passo",
    quickBrief: "Sinal da conta",
    salesRepName: "Lucas Mendes",
    salesRepRole: "SDR",
    sidebarTitle: "Birth Hub 360",
    spinLabel: "Sugestoes SPIN",
    summaryLabel: "Rota de conversao",
    tableAction: "Acoes",
    tableLead: "Lead",
    tablePriority: "Prioridade",
    tableScore: "Lead score",
    tableSource: "Origem",
    timelineLabel: "Encaixe de agenda"
  }
};

export const SDR_AUTOMATIC_LEADS: Record<SupportedLocale, SdrAutomaticLead[]> = {
  "en-US": [
    {
      action: "Call now",
      company: "Connecta Corp",
      createdAt: "2026-04-15T08:05:00.000Z",
      email: "julia.andrade@connectacorp.com",
      id: "lead_julia_andrade",
      name: "Julia Andrade",
      owner: "Lucas Mendes",
      priority: "Critical",
      priorityTone: "critical",
      role: "Marketing Director",
      score: 98,
      slaDueAt: "2026-04-15T09:20:00.000Z",
      slaStatus: "breached",
      source: "Downloaded \"Sales 4.0\" ebook",
      stage: "proposal"
    },
    {
      action: "Qualify",
      company: "LogiBrasil",
      createdAt: "2026-04-15T09:12:00.000Z",
      email: "fernando.costa@logibrasil.com",
      id: "lead_fernando_costa",
      name: "Fernando Costa",
      owner: "Marina Lopes",
      priority: "High",
      priorityTone: "high",
      role: "IT Manager",
      score: 82,
      slaDueAt: "2026-04-15T13:00:00.000Z",
      slaStatus: "watch",
      source: "Webinar registration",
      stage: "qualified"
    },
    {
      action: "Open sequence",
      company: "Midia Sul",
      createdAt: "2026-04-14T18:42:00.000Z",
      email: "patricia.nogueira@midiasul.com.br",
      id: "lead_patricia_nogueira",
      name: "Patricia Nogueira",
      owner: "Renato Alves",
      priority: "Warm",
      priorityTone: "warm",
      role: "Revenue Ops Lead",
      score: 74,
      slaDueAt: "2026-04-15T16:00:00.000Z",
      slaStatus: "healthy",
      source: "Intent signal on pricing page",
      stage: "new"
    },
    {
      action: "Book demo",
      company: "Nexa Health",
      createdAt: "2026-04-14T15:20:00.000Z",
      email: "carla.souza@nexahealth.io",
      id: "lead_carla_souza",
      name: "Carla Souza",
      owner: "Lucas Mendes",
      priority: "Critical",
      priorityTone: "critical",
      role: "Revenue Director",
      score: 94,
      slaDueAt: "2026-04-15T11:30:00.000Z",
      slaStatus: "watch",
      source: "Inbound demo request",
      stage: "demo"
    },
    {
      action: "Send proposal",
      company: "Atlas Tech",
      createdAt: "2026-04-13T14:10:00.000Z",
      email: "marcos.lima@atlastch.com",
      id: "lead_marcos_lima",
      name: "Marcos Lima",
      owner: "Marina Lopes",
      priority: "High",
      priorityTone: "high",
      role: "Commercial Manager",
      score: 88,
      slaDueAt: "2026-04-16T10:00:00.000Z",
      slaStatus: "healthy",
      source: "Partner referral",
      stage: "proposal"
    },
    {
      action: "Revive opportunity",
      company: "Studio Norte",
      createdAt: "2026-04-12T11:55:00.000Z",
      email: "ana.ribeiro@studionorte.com",
      id: "lead_ana_ribeiro",
      name: "Ana Ribeiro",
      owner: "Renato Alves",
      priority: "Warm",
      priorityTone: "warm",
      role: "Growth Manager",
      score: 72,
      slaDueAt: "2026-04-15T18:30:00.000Z",
      slaStatus: "healthy",
      source: "Retargeting campaign",
      stage: "qualified"
    },
    {
      action: "Negotiate terms",
      company: "Prime Industrial",
      createdAt: "2026-04-11T16:08:00.000Z",
      email: "rafael.castro@primeindustrial.com",
      id: "lead_rafael_castro",
      name: "Rafael Castro",
      owner: "Lucas Mendes",
      priority: "Critical",
      priorityTone: "critical",
      role: "Operations VP",
      score: 91,
      slaDueAt: "2026-04-15T10:45:00.000Z",
      slaStatus: "breached",
      source: "Outbound account-based sequence",
      stage: "negotiation"
    },
    {
      action: "Research account",
      company: "Orbit Labs",
      createdAt: "2026-04-10T09:40:00.000Z",
      email: "bia.ferreira@orbitlabs.ai",
      id: "lead_bia_ferreira",
      name: "Bia Ferreira",
      owner: "Marina Lopes",
      priority: "High",
      priorityTone: "high",
      role: "Head of Product",
      score: 84,
      slaDueAt: "2026-04-15T15:10:00.000Z",
      slaStatus: "watch",
      source: "Founder referral",
      stage: "new"
    },
    {
      action: "Confirm champion",
      company: "BluePeak",
      createdAt: "2026-04-09T13:18:00.000Z",
      email: "diego.silva@bluepeak.co",
      id: "lead_diego_silva",
      name: "Diego Silva",
      owner: "Renato Alves",
      priority: "Warm",
      priorityTone: "warm",
      role: "Sales Ops Manager",
      score: 76,
      slaDueAt: "2026-04-16T09:15:00.000Z",
      slaStatus: "healthy",
      source: "Community referral",
      stage: "qualified"
    },
    {
      action: "Advance to demo",
      company: "Nova Energia",
      createdAt: "2026-04-08T17:26:00.000Z",
      email: "helena.martins@novaenergia.com.br",
      id: "lead_helena_martins",
      name: "Helena Martins",
      owner: "Lucas Mendes",
      priority: "High",
      priorityTone: "high",
      role: "Commercial Strategy Lead",
      score: 86,
      slaDueAt: "2026-04-15T19:00:00.000Z",
      slaStatus: "healthy",
      source: "Intent data from comparison page",
      stage: "demo"
    }
  ],
  "pt-BR": [
    {
      action: "Ligar agora",
      company: "Connecta Corp",
      createdAt: "2026-04-15T08:05:00.000Z",
      email: "julia.andrade@connectacorp.com",
      id: "lead_julia_andrade",
      name: "Julia Andrade",
      owner: "Lucas Mendes",
      priority: "Critica",
      priorityTone: "critical",
      role: "Diretora de Marketing",
      score: 98,
      slaDueAt: "2026-04-15T09:20:00.000Z",
      slaStatus: "breached",
      source: "Download do ebook \"Vendas 4.0\"",
      stage: "proposal"
    },
    {
      action: "Qualificar",
      company: "LogiBrasil",
      createdAt: "2026-04-15T09:12:00.000Z",
      email: "fernando.costa@logibrasil.com",
      id: "lead_fernando_costa",
      name: "Fernando Costa",
      owner: "Marina Lopes",
      priority: "Alta",
      priorityTone: "high",
      role: "Gerente de TI",
      score: 82,
      slaDueAt: "2026-04-15T13:00:00.000Z",
      slaStatus: "watch",
      source: "Inscricao em webinar",
      stage: "qualified"
    },
    {
      action: "Abrir cadencia",
      company: "Midia Sul",
      createdAt: "2026-04-14T18:42:00.000Z",
      email: "patricia.nogueira@midiasul.com.br",
      id: "lead_patricia_nogueira",
      name: "Patricia Nogueira",
      owner: "Renato Alves",
      priority: "Quente",
      priorityTone: "warm",
      role: "Lider de RevOps",
      score: 74,
      slaDueAt: "2026-04-15T16:00:00.000Z",
      slaStatus: "healthy",
      source: "Sinal de intencao na pagina de precos",
      stage: "new"
    },
    {
      action: "Agendar demo",
      company: "Nexa Health",
      createdAt: "2026-04-14T15:20:00.000Z",
      email: "carla.souza@nexahealth.io",
      id: "lead_carla_souza",
      name: "Carla Souza",
      owner: "Lucas Mendes",
      priority: "Critica",
      priorityTone: "critical",
      role: "Diretora de Receita",
      score: 94,
      slaDueAt: "2026-04-15T11:30:00.000Z",
      slaStatus: "watch",
      source: "Pedido inbound de demonstracao",
      stage: "demo"
    },
    {
      action: "Enviar proposta",
      company: "Atlas Tech",
      createdAt: "2026-04-13T14:10:00.000Z",
      email: "marcos.lima@atlastch.com",
      id: "lead_marcos_lima",
      name: "Marcos Lima",
      owner: "Marina Lopes",
      priority: "Alta",
      priorityTone: "high",
      role: "Gerente Comercial",
      score: 88,
      slaDueAt: "2026-04-16T10:00:00.000Z",
      slaStatus: "healthy",
      source: "Indicacao de parceiro",
      stage: "proposal"
    },
    {
      action: "Reativar oportunidade",
      company: "Studio Norte",
      createdAt: "2026-04-12T11:55:00.000Z",
      email: "ana.ribeiro@studionorte.com",
      id: "lead_ana_ribeiro",
      name: "Ana Ribeiro",
      owner: "Renato Alves",
      priority: "Quente",
      priorityTone: "warm",
      role: "Gerente de Growth",
      score: 72,
      slaDueAt: "2026-04-15T18:30:00.000Z",
      slaStatus: "healthy",
      source: "Campanha de retargeting",
      stage: "qualified"
    },
    {
      action: "Negociar termos",
      company: "Prime Industrial",
      createdAt: "2026-04-11T16:08:00.000Z",
      email: "rafael.castro@primeindustrial.com",
      id: "lead_rafael_castro",
      name: "Rafael Castro",
      owner: "Lucas Mendes",
      priority: "Critica",
      priorityTone: "critical",
      role: "VP de Operacoes",
      score: 91,
      slaDueAt: "2026-04-15T10:45:00.000Z",
      slaStatus: "breached",
      source: "Cadencia outbound ABM",
      stage: "negotiation"
    },
    {
      action: "Pesquisar conta",
      company: "Orbit Labs",
      createdAt: "2026-04-10T09:40:00.000Z",
      email: "bia.ferreira@orbitlabs.ai",
      id: "lead_bia_ferreira",
      name: "Bia Ferreira",
      owner: "Marina Lopes",
      priority: "Alta",
      priorityTone: "high",
      role: "Head de Produto",
      score: 84,
      slaDueAt: "2026-04-15T15:10:00.000Z",
      slaStatus: "watch",
      source: "Indicacao de founder",
      stage: "new"
    },
    {
      action: "Confirmar champion",
      company: "BluePeak",
      createdAt: "2026-04-09T13:18:00.000Z",
      email: "diego.silva@bluepeak.co",
      id: "lead_diego_silva",
      name: "Diego Silva",
      owner: "Renato Alves",
      priority: "Quente",
      priorityTone: "warm",
      role: "Gerente de Sales Ops",
      score: 76,
      slaDueAt: "2026-04-16T09:15:00.000Z",
      slaStatus: "healthy",
      source: "Indicacao da comunidade",
      stage: "qualified"
    },
    {
      action: "Avancar para demo",
      company: "Nova Energia",
      createdAt: "2026-04-08T17:26:00.000Z",
      email: "helena.martins@novaenergia.com.br",
      id: "lead_helena_martins",
      name: "Helena Martins",
      owner: "Lucas Mendes",
      priority: "Alta",
      priorityTone: "high",
      role: "Lider de Estrategia Comercial",
      score: 86,
      slaDueAt: "2026-04-15T19:00:00.000Z",
      slaStatus: "healthy",
      source: "Intent data na pagina comparativa",
      stage: "demo"
    }
  ]
};

export const SDR_AUTOMATIC_TIME_SLOTS: SdrAutomaticTimeSlot[] = [
  { label: "09:30", recommended: true },
  { label: "11:00" },
  { label: "14:30" },
  { label: "16:00" }
];
